name: umbrella-deploy

on:
  push:
    branches:
      - main
      - helmfile

jobs:
  configure-cluster-type:
    outputs:
      cluster_type: ${{ steps.set_cluster_type.outputs.cluster_type }}
    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set env name to staging
        uses: allenevans/set-env@v2.0.0
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        with:
          CLUSTER_TYPE: production
      - name: Set env name to development
        uses: allenevans/set-env@v2.0.0
        if: ${{ steps.extract_branch.outputs.branch != 'main' }}
        with:
          CLUSTER_TYPE: development
      - run: |
          echo "cluster type selected: ${CLUSTER_TYPE}"
      - name: Set cluster type
        id: set_cluster_type
        shell: bash
        # Derive cluster type name from branch name, fallback on 'development'
        # ENV_main -> development
        # ENV_production -> production
        # ENV_* -> development
        run: |
          echo "##[set-output name=cluster_type;]$(echo $CLUSTER_TYPE)"
  upgrade_runtime:
    strategy:
      matrix:
        include:
          - cluster_name: andy
            cluster_type: development
    needs:
      - configure-cluster-type
    steps:
      - uses: actions/checkout@v2
      - name: Sync Helmfile
        uses: ./.github/actions/helmfile
        id: sync-helmfile
        if: ${{ matrix.cluster_type == needs.configure-cluster-type.outputs.cluster_type }}
        with:
          aws-access-key-id: ${{ inputs.deployerAWSAccessKeyID }}
          aws-secret-access-key: ${{ inputs.deployerAWSSecretAccessKey }}
          aws-region: us-east-2
          cluster-name: ${{ matrix.cluster_name }}
          helmfile-environment: ${{ matrix.cluster_name }}
